### PR TITLE
Handle wide char varchars

### PR DESCRIPTION
**Pull request by frubi**

### CODE REVIEW

**Comment by kstrauser** [comment]
Hi @frubi, thanks for the PR! I'm going camping this weekend but I'll take a look at this when I get back.

BTW, I'm working to add a standard test suite so we can do regression checks. Could you create a sample database with wide char fields and a couple of records?

**Comment by frubi** [comment]
Hi kstrauser, i uploaded a [little test file with wide char varchars](https://github.com/kstrauser/pgdbf/files/60554/pgdbf-wchar-test.zip). Unfortunately i have no control over the database creation, so some values are redacted.

```
$ pgdbf -s UTF-16 -R wchar/SystemParameter.dbf 
BEGIN;
SET statement_timeout=60000; DROP TABLE IF EXISTS systemparameter; SET statement_timeout=0;
CREATE TABLE systemparameter (paraname VARCHAR(64), paravalue VARCHAR(64));
\COPY systemparameter FROM STDIN
ModelVersion	6
VersionIncrement	1
ProductVersion	XXXXXXXX
ExporterVersion	XXXXXXX-XXXXXXXX-XXXXXX
ExportTimestamp	11/11/2015 10:33:15
UserName	ppadmin
DBUsername	ppadmin
DBName	XXXXXXXXXXXX
HostName	XXXXXXXX
GDMBaseVersion	XXXXXXXX
ExportMode	1FileProKnoten
ExportNr	5012
ExportKurzBez	XXXX
ExportLangBez	XXXXXXXXXXXXXXXXXXXXXX
\.
COMMIT;
```

**Comment by kstrauser** [comment]
Can this file be added to the public repo?

**Comment by frubi** [comment]
Yes, you can add the test file to a public repo.

**Comment by kstrauser** [comment]
Oh, one last thing! Would you add yourself to README.mdown? You don't have to, but you should have credit for your work.

**Pull request merged**
